add function `encrypt_with_gocd`

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -2,7 +2,7 @@
 
 set -e
 if [[ ! -f ./releaser ]];then
-  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.3/releaser
+  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.3/releaser || { echo "cannot download releaser"; }
 fi
 source ./releaser
 releaser_init
