add functions encrypt_with_gocd2 and generate_certs_token2
so that we do not write to hidden bash variables

diff --git a/src/secret-ops b/src/secret-ops
--- a/src/secret-ops
+++ b/src/secret-ops
@@ -30,6 +30,7 @@ export VAULT_ADDR="${VAULT_ADDR:-https://vault.ai-traders.com:8200}"
 
 # Encrypts any string, uses GoCD server.
 function encrypt_with_gocd {
+  secret_ops_log_warn "Using obsolete function: encrypt_with_gocd, use encrypt_with_gocd2 instead"
   variable_to_encrypt=$1
 
   #FIXME: curl to go server is insecure because go uses self-signed certs
@@ -51,15 +52,55 @@ function encrypt_with_gocd {
   secured_value=$(echo $HTTP_BODY | jq '.encrypted_value')
 }
 
+# Encrypts any string, uses GoCD server.
+function encrypt_with_gocd2 {
+  local variable_to_encrypt=$1
+
+  #FIXME: curl to go server is insecure because go uses self-signed certs
+  # this token has privileges to issue ai-traders.com certificates
+  local my_gocd_pass=$(vault read -field=value secret/$USER/gocd)
+  local HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+    'https://go.ai-traders.com:8154/go/api/admin/encrypt' --insecure  \
+    -u "${USER}:${my_gocd_pass}" \
+    -H 'Accept: application/vnd.go.cd.v1+json' \
+    -H 'Content-Type: application/json' \
+    -X POST -d "{ \"value\" : \"${variable_to_encrypt}\" }")
+  # extract the status
+  local HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+  if [ ! $HTTP_STATUS -eq 200  ]; then
+    echo "Error encrypting token for gocd [HTTP status: $HTTP_STATUS]" >&2
+    exit 1
+  fi
+  local HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+  echo $HTTP_BODY | jq '.encrypted_value'
+}
+
 # Encrypts Vault Token.
 function generate_certs_token {
+  secret_ops_log_warn "Using obsolete function: generate_certs_token, use generate_certs_token2 instead"
   vault_token=$(vault token create -policy=issue-ait-certs -field token)
   encrypt_with_gocd "${vault_token}"
   secured_token_gocd=${secured_value}
   echo "Generated token and secured for gocd"
 }
 
+# Encrypts Vault Token.
+function generate_certs_token2 {
+  local vault_token=$(vault token create -policy=issue-ait-certs -field token)
+  local secured_token_gocd=$(encrypt_with_gocd2 "${vault_token}")
+  echo "Generated token and secured for gocd" >&2
+  echo "${secured_token_gocd}"
+}
+
 function insert_vault_token_gocd_yaml {
+  echo "Replacing pipeline config with with VAULT_TOKEN: ${secured_token_gocd}"
+  find . -name '*.gocd.yaml' -exec sed -i -E "s#VAULT_TOKEN\:.*#VAULT_TOKEN: ${secured_token_gocd}#g" {} \;
+}
+
+function insert_vault_token_gocd_yaml2 {
+  local secured_token_gocd=$1
+
+  secret_ops_log_warn "Using obsolete function: insert_vault_token_gocd_yaml, use insert_vault_token_gocd_yaml2 instead"
   echo "Replacing pipeline config with with VAULT_TOKEN: ${secured_token_gocd}"
   find . -name '*.gocd.yaml' -exec sed -i -E "s#VAULT_TOKEN\:.*#VAULT_TOKEN: ${secured_token_gocd}#g" {} \;
 }
