add functions with prefix: `secret_ops::`

diff --git a/src/secret-ops b/src/secret-ops
--- a/src/secret-ops
+++ b/src/secret-ops
@@ -6,31 +6,47 @@
 # with stdout. (Curl does the same).
 ################################################################################
 
-secret_ops_program_name() {
+secret_ops::program_name() {
   echo "SECRET-OPS"
 }
-secret_ops_log_debug() {
+secret_ops_program_name() {
+  secret_ops::program_name
+}
+secret_ops::log_debug() {
   if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
-    echo -e "$(date "+%d-%m-%Y %T") $(secret_ops_program_name) debug: ${1}" >&2
+    echo -e "$(date "+%d-%m-%Y %T") $(secret_ops::program_name) debug: ${1}" >&2
   fi
 }
+secret_ops_log_debug() {
+  secret_ops::log_debug $1
+}
+secret_ops::log_info() {
+  echo -e "$(date "+%d-%m-%Y %T") $(secret_ops::program_name) info: ${1}" >&2
+}
 secret_ops_log_info() {
-  echo -e "$(date "+%d-%m-%Y %T") $(secret_ops_program_name) info: ${1}" >&2
+  secret_ops::log_info $1
+}
+secret_ops::log_error() {
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: $1\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
 }
 secret_ops_log_error() {
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: $1\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
+  secret_ops::log_error $1
+}
+secret_ops::log_warn() {
+  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) warn: $1\e[0m" >&2
 }
 secret_ops_log_warn() {
-  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) warn: $1\e[0m" >&2
+  secret_ops::log_warn $1
 }
 
 export VAULT_ADDR="${VAULT_ADDR:-https://vault.ai-traders.com:8200}"
 
+# obsolete function
 # Encrypts any string, uses GoCD server.
 function encrypt_with_gocd {
-  secret_ops_log_warn "Using obsolete function: encrypt_with_gocd, use encrypt_with_gocd2 instead"
+  secret_ops::log_warn "Using obsolete function: encrypt_with_gocd, use encrypt_with_gocd2 instead"
   variable_to_encrypt=$1
 
   #FIXME: curl to go server is insecure because go uses self-signed certs
@@ -53,7 +69,7 @@ function encrypt_with_gocd {
 }
 
 # Encrypts any string, uses GoCD server.
-function encrypt_with_gocd2 {
+function secret_ops::encrypt_with_gocd_top {
   local variable_to_encrypt=${1?variable_to_encrypt not set}
 
   url_dir="${USER}"
@@ -64,13 +80,19 @@ function encrypt_with_gocd2 {
   my_gocd_pass=$(vault read -field=value secret/${url_dir}/gocd_password)
   if [[ $? != "0" ]]; then exit 1; fi
 
-  encrypt_with_gocd_common "${variable_to_encrypt}" "go.ai-traders.com" "-u ${USER}:${my_gocd_pass}"
+  secret_ops::encrypt_with_gocd_common "${variable_to_encrypt}" "go.ai-traders.com" "-u ${USER}:${my_gocd_pass}"
+}
+function encrypt_with_gocd2 {
+  secret_ops::encrypt_with_gocd_top $1
+}
+function secret_ops::encrypt_with_gocd_base {
+  local variable_to_encrypt=${1?variable_to_encrypt not set}
+  secret_ops::encrypt_with_gocd_common "${variable_to_encrypt}" "go2.ai-traders.com" ""
 }
 function encrypt_with_gocd_base {
-  local variable_to_encrypt=${1?variable_to_encrypt not set}
-  encrypt_with_gocd_common "${variable_to_encrypt}" "go2.ai-traders.com" ""
+  secret_ops::encrypt_with_gocd_base $1
 }
-function encrypt_with_gocd_common {
+function secret_ops::encrypt_with_gocd_common {
   local variable_to_encrypt=${1?variable_to_encrypt not set}
   local gocd_url=${2?gocd_url not set}
   local credentials=${3?credentials not set}
@@ -92,33 +114,45 @@ function encrypt_with_gocd_common {
   local HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
   echo $HTTP_BODY | jq '.encrypted_value'
 }
+function encrypt_with_gocd_common {
+  secret_ops::encrypt_with_gocd_common $1 $2 $3
+}
 
 # Encrypts Vault Token.
-function generate_certs_token {
-  secret_ops_log_warn "Using obsolete function: generate_certs_token, use generate_certs_token2 instead"
+function secret_ops::generate_certs_token {
+  secret_ops::log_warn "Using obsolete function: generate_certs_token, use generate_certs_token2 instead"
   vault_token=$(vault token create -policy=issue-ait-certs -field token)
   encrypt_with_gocd "${vault_token}"
   secured_token_gocd=${secured_value}
   echo "Generated token and secured for gocd"
 }
+function generate_certs_token {
+  secret_ops::generate_certs_token
+}
 
 # Encrypts Vault Token.
-function generate_certs_token2 {
+function secret_ops::generate_certs_token_gocd_top {
   local vault_token=$(vault token create -policy=issue-ait-certs -field token)
-  local secured_token_gocd=$(encrypt_with_gocd2 "${vault_token}")
+  local secured_token_gocd=$(secret_ops::encrypt_with_gocd_top "${vault_token}")
   echo "Generated token and secured for gocd" >&2
   echo "${secured_token_gocd}"
 }
+function generate_certs_token2 {
+  secret_ops::generate_certs_token_gocd_top
+}
 
 function insert_vault_token_gocd_yaml {
+  secret_ops::log_warn "Using obsolete function: insert_vault_token_gocd_yaml, use insert_vault_token_gocd_yaml2 instead"
   echo "Replacing pipeline config with with VAULT_TOKEN: ${secured_token_gocd}"
   find . -name '*.gocd.yaml' -exec sed -i -E "s#VAULT_TOKEN\:.*#VAULT_TOKEN: ${secured_token_gocd}#g" {} \;
 }
 
-function insert_vault_token_gocd_yaml2 {
-  local secured_token_gocd=$1
+function secret_ops::insert_vault_token_gocd_yaml {
+  local secured_token_gocd=${1?secured_token_gocd not set}
 
-  secret_ops_log_warn "Using obsolete function: insert_vault_token_gocd_yaml, use insert_vault_token_gocd_yaml2 instead"
   echo "Replacing pipeline config with with VAULT_TOKEN: ${secured_token_gocd}"
   find . -name '*.gocd.yaml' -exec sed -i -E "s#VAULT_TOKEN\:.*#VAULT_TOKEN: ${secured_token_gocd}#g" {} \;
+}
+function insert_vault_token_gocd_yaml2 {
+  secret_ops::insert_vault_token_gocd_yaml  $1
 }
diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -1,27 +1,28 @@
 #!/bin/bash
 
-set -e
-if [[ ! -f ./releaser ]];then
-  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.3/releaser || { echo "cannot download releaser"; }
+set -Eeo pipefail
+if [[ ! -f ./releaser ]]; then
+  wget --quiet http://http.archive.ai-traders.com/releaser/1.1.0/releaser || { echo "Cannot download releaser, ignoring."; }
 fi
-source ./releaser
-releaser_init
+if [[ -f ./releaser ]]; then
+  source ./releaser
+fi
 
 command="$1"
 case "${command}" in
   set_version)
       if [[ -n "$2" ]]; then
         next_version="$2"
-        set_version_in_changelog "${changelog_file}" "${next_version}"
-        set_next_oversion "${next_version}"
+        releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
+        releaser::set_next_oversion "${next_version}"
       else
-        next_version=$(get_next_oversion)
-        set_version_in_changelog "${changelog_file}" "${next_version}"
+        next_version=$(releaser::get_next_oversion)
+        releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
       fi
       exit $?
       ;;
   verify_version)
-      verify_version_for_release
+      releaser::verify_version_for_release
       exit $?
       ;;
   test_bash)
@@ -33,16 +34,16 @@ case "${command}" in
       exit $?
       ;;
   release)
-      verify_version_for_release
-      git_tag_from_oversion
-      old_version=$(get_next_oversion)
-      next_version=$(bump_patch_version "${old_version}")
-      set_next_oversion "${next_version}"
+      releaser::verify_version_for_release
+      releaser::git_tag_from_oversion
+      old_version=$(releaser::get_next_oversion)
+      next_version=$(releaser::bump_patch_version "${old_version}")
+      releaser::set_next_oversion "${next_version}"
       exit $?
       ;;
   _publish)
       # publish the just released version
-      version=$(get_last_git_tagged_version)
+      version=$(releaser::get_last_git_tagged_version)
       export OS_TENANT_NAME=ait-production
       export OS_PROJECT_NAME=ait-production
       file="src/secret-ops"
