fix logging functions so that their names are unique

diff --git a/src/secret-ops b/src/secret-ops
--- a/src/secret-ops
+++ b/src/secret-ops
@@ -6,24 +6,24 @@
 # with stdout. (Curl does the same).
 ################################################################################
 
-program_name() {
+secret_ops_program_name() {
   echo "SECRET-OPS"
 }
-log_debug() {
+secret_ops_log_debug() {
   if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
-    echo -e "$(date "+%d-%m-%Y %T") $(program_name) debug: ${1}" >&2
+    echo -e "$(date "+%d-%m-%Y %T") $(secret_ops_program_name) debug: ${1}" >&2
   fi
 }
-log_info() {
-  echo -e "$(date "+%d-%m-%Y %T") $(program_name) info: ${1}" >&2
+secret_ops_log_info() {
+  echo -e "$(date "+%d-%m-%Y %T") $(secret_ops_program_name) info: ${1}" >&2
 }
-log_error() {
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: $1\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
+secret_ops_log_error() {
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: $1\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
 }
-log_warn() {
-  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(program_name) warn: $1\e[0m" >&2
+secret_ops_log_warn() {
+  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(secret_ops_program_name) warn: $1\e[0m" >&2
 }
 
 export VAULT_ADDR="${VAULT_ADDR:-https://vault.ai-traders.com:8200}"
